# Generated by Django 5.0.6 on 2024-05-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoGestores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NivelOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_orgao_principal', models.CharField(max_length=100)),
                ('sigla_orgao', models.CharField(max_length=10)),
                ('inicio_atividades', models.DateField()),
                ('termino_atividades', models.DateField()),
                ('periodo_historico', models.CharField(max_length=100)),
                ('fundamentacao_legal', models.TextField()),
                ('upload_fundamentacao', models.FileField(upload_to='fundamentacao/')),
                ('dados_biograficos', models.TextField()),
                ('observacao', models.TextField()),
                ('cargo_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.cargogestores')),
            ],
        ),
        migrations.AddField(
            model_name='cargogestores',
            name='nivel_operacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.niveloperacional'),
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_orgao', models.CharField(max_length=100)),
                ('sigla_orgao', models.CharField(max_length=10)),
                ('inicio_atividades', models.DateField()),
                ('termino_atividades', models.DateField()),
                ('fundamentacao_legal', models.TextField()),
                ('upload_fundamentacao', models.FileField(upload_to='fundamentacao/')),
                ('observacao', models.TextField()),
                ('cargo_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.cargogestores')),
                ('orgao_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.orgao')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(max_length=100)),
                ('sigla_unidade', models.CharField(max_length=10)),
                ('cargo_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.cargogestores')),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.orgao')),
                ('unidade_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.unidadeadministrativa')),
            ],
        ),
    ]
