# Generated by Django 5.0.6 on 2024-05-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historico',
            new_name='GestaoPrincial',
        ),
    ]
