# Generated by Django 5.0.6 on 2024-05-24 14:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0003_gestorestruturaprincipal_orgao_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_pais', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='gestorestruturaprincipal',
            name='nascimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='gestorestruturaprincipal',
            name='nacionalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.paises'),
        ),
    ]
