# Generated by Django 5.0.6 on 2024-05-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0005_remove_gestorestruturaprincipal_nacionalidade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CargoGestores',
            new_name='CargoGestao',
        ),
        migrations.RenameModel(
            old_name='Paises',
            new_name='Pais',
        ),
    ]
