# Generated by Django 5.0.6 on 2024-06-02 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0006_rename_cargogestores_cargogestao_rename_paises_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(blank=True, max_length=10)),
                ('inicio_responsabilidade', models.DateField()),
                ('fim_responsabilidade', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cargogestao',
            name='nivel_operacional',
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='cargo_gestor',
        ),
        migrations.RemoveField(
            model_name='unidadeadministrativa',
            name='cargo_gestor',
        ),
        migrations.RemoveField(
            model_name='gestaoprincial',
            name='cargo_gestor',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='gestorestruturaprincipal',
            name='naturalidade',
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='orgao_superior',
        ),
        migrations.RemoveField(
            model_name='unidadeadministrativa',
            name='orgao',
        ),
        migrations.RemoveField(
            model_name='unidadeadministrativa',
            name='unidade_superior',
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('data_obito', models.DateField(blank=True, null=True)),
                ('inicio_mandato', models.DateField()),
                ('fim_mandato', models.DateField(blank=True, null=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facetas.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facetas.organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos')),
                ('periodo_administrativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facetas.periodoadministrativo')),
            ],
        ),
        migrations.DeleteModel(
            name='NivelOperacional',
        ),
        migrations.DeleteModel(
            name='CargoGestao',
        ),
        migrations.DeleteModel(
            name='GestaoPrincial',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='GestorEstruturaPrincipal',
        ),
        migrations.DeleteModel(
            name='Orgao',
        ),
        migrations.DeleteModel(
            name='UnidadeAdministrativa',
        ),
    ]
