# Generated by Django 5.0.6 on 2024-06-07 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0007_organizacao_remove_cargogestao_nivel_operacional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='organizacao',
        ),
        migrations.RemoveField(
            model_name='periodoadministrativo',
            name='organizacao',
        ),
        migrations.CreateModel(
            name='OrgaoAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_atual', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=50)),
                ('inicio_atividades', models.DateField()),
                ('fim_atividades', models.DateField(blank=True, null=True)),
                ('orgao_antecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.orgaoatual')),
            ],
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
        migrations.DeleteModel(
            name='Organizacao',
        ),
        migrations.DeleteModel(
            name='PeriodoAdministrativo',
        ),
    ]
