# Generated by Django 5.0.6 on 2024-06-07 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0008_remove_gestor_organizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoGestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('data_nascimento', models.DateField()),
                ('data_obito', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='orgaoatual',
            options={'verbose_name_plural': 'Faceta do Todo'},
        ),
        migrations.AlterField(
            model_name='orgaoatual',
            name='orgao_antecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.orgaoatual', verbose_name='Órgão antecessor'),
        ),
        migrations.AlterField(
            model_name='orgaoatual',
            name='orgao_atual',
            field=models.CharField(max_length=150, verbose_name='Órgão Atual'),
        ),
        migrations.CreateModel(
            name='GestorMaior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('data_obito', models.DateField(blank=True, null=True)),
                ('cargo_gestao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.cargogestao', verbose_name='Cargo de Gestão')),
                ('nome_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.tabelagestor', verbose_name='Nome do Gestor')),
            ],
        ),
    ]
