# Generated by Django 5.0.6 on 2024-06-07 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0009_cargogestao_tabelagestor_alter_orgaoatual_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacao', models.CharField(max_length=250, verbose_name='Denominação do Perído Histórico')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('doc_fundamento', models.FileField(blank=True, null=True, upload_to='')),
                ('obs', models.TextField(blank=True, null=True)),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.orgaoatual', verbose_name='Orgão do Período')),
            ],
        ),
    ]
