# Generated by Django 5.0.6 on 2024-06-07 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0010_periodohistorico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgaoatual',
            options={'verbose_name_plural': 'Organizações do Todo'},
        ),
        migrations.AlterModelOptions(
            name='periodohistorico',
            options={'verbose_name_plural': 'Faceta do Todo'},
        ),
        migrations.AddField(
            model_name='periodohistorico',
            name='gestor_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.gestormaior', verbose_name='Gestor'),
        ),
    ]
