# Generated by Django 5.0.6 on 2024-06-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0011_alter_orgaoatual_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAdminstracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominação', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Faceta do Todo',
            },
        ),
        migrations.CreateModel(
            name='OrgaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgao_unidade', models.CharField(max_length=150, verbose_name='Órgão Atual')),
                ('sigla', models.CharField(max_length=50)),
                ('inicio_atividades', models.DateField()),
                ('fim_atividades', models.DateField(blank=True, null=True)),
                ('orgao_antecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.orgaounidade', verbose_name='Vinculo Superior')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.periodohistorico', verbose_name='Órgão/ Período Histórico')),
                ('tipo_administracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.tipoadminstracao', verbose_name='Tipo da Administração')),
            ],
        ),
    ]
