# Generated by Django 5.0.6 on 2024-06-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0012_tipoadminstracao_orgaounidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgaounidade',
            name='atribuicoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgaounidade',
            name='orgao_unidade',
            field=models.CharField(max_length=150, verbose_name='Órgão / Unidade'),
        ),
    ]
