# Generated by Django 5.0.6 on 2024-06-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0016_alter_periodohistorico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, verbose_name='Espécie Documental')),
                ('Descrição', models.TextField(blank=True, null=True)),
                ('multiplo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'ESPÉCIES DOCUMENTAIS',
            },
        ),
        migrations.CreateModel(
            name='GuardaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'PRAZO DE GUARDAS FASE CORRENTE',
                'ordering': ['guarda'],
            },
        ),
        migrations.CreateModel(
            name='GuardaIntermediario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'PRAZO DE GUARDA FASE INTERMEDIARIA',
                'ordering': ['guarda'],
            },
        ),
        migrations.CreateModel(
            name='PrazoDeGuarda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80)),
                ('tempo', models.IntegerField(verbose_name='Quantos anos de guarda')),
            ],
            options={
                'verbose_name_plural': 'PRAZOS DE GUARDA',
                'ordering': ['tempo', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='TermoRemissivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_remissivo', models.CharField(max_length=200, verbose_name='Termo Remissivo')),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Termos Remissivos',
                'ordering': ['termo_remissivo'],
            },
        ),
        migrations.AlterModelOptions(
            name='configuracaofuncional',
            options={'verbose_name_plural': '04 - Faceta Funcional'},
        ),
        migrations.CreateModel(
            name='ClasseTTDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade_fim', models.CharField(choices=[('ATIVIDADE-FIM', 'atividade-fim'), ('ATIVIDADE-MEIO', 'atividade-meio')], max_length=15, verbose_name='Atividade')),
                ('cod', models.CharField(max_length=7, verbose_name='Código Classificação')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição do assunto')),
                ('permanente', models.CharField(blank=True, choices=[('GUARDA PERMANENTE', 'Guarda Permanente'), ('ELIMINAÇÃO', 'Eliminação')], max_length=25, null=True, verbose_name='Destinação,')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.classettdd')),
                ('tempo_fase_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.guardacorrente')),
                ('tempo_fase_intemediario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.guardaintermediario')),
            ],
            options={
                'verbose_name_plural': 'CLASSIFICAÇÕES TABELA DE TEMPORALIDADE',
                'ordering': ['cod'],
            },
        ),
        migrations.CreateModel(
            name='NormaEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.especie', verbose_name='Espécie da Norma')),
            ],
        ),
        migrations.CreateModel(
            name='NormaTipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma_tipologia', models.CharField(max_length=200, verbose_name='Norma fudamenta tipologia')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.normaespecie', verbose_name='Espécie')),
            ],
            options={
                'verbose_name_plural': 'Normas da tipologia',
                'ordering': ['norma_tipologia'],
            },
        ),
        migrations.AddField(
            model_name='guardaintermediario',
            name='guarda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.prazodeguarda', verbose_name='Prazo faser intermediaria'),
        ),
        migrations.AddField(
            model_name='guardacorrente',
            name='guarda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.prazodeguarda', verbose_name='Prazo fase corrente'),
        ),
        migrations.CreateModel(
            name='TipologiaDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia_adotado', models.CharField(max_length=300)),
                ('grau_de_acesso', models.CharField(blank=True, choices=[('OSTENSIVO', 'Ostensivo'), ('RESTRITO', 'Restrito')], default='OSTENSIVO', max_length=9, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('classificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.classettdd', verbose_name='Classificação')),
                ('especie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.especie', verbose_name='Espécie')),
                ('norma_tipologia', models.ManyToManyField(to='facetas.normatipologia')),
                ('termo_remissivo', models.ManyToManyField(to='facetas.termoremissivo')),
            ],
            options={
                'verbose_name_plural': 'TIPOLOGIAS',
            },
        ),
    ]
