# Generated by Django 4.2.13 on 2024-06-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0017_especie_guardacorrente_guardaintermediario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipologiadocumental',
            options={'verbose_name_plural': '05 - Faceta Tipologia documental'},
        ),
    ]
