# Generated by Django 5.0.6 on 2024-06-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetas', '0018_alter_tipologiadocumental_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodohistorico',
            options={'verbose_name_plural': '01 - Faceta Histórica da Instituição (Todo)'},
        ),
        migrations.AlterModelOptions(
            name='periodohistoricoparte',
            options={'verbose_name_plural': '02 - Faceta História do Órgão/Unidade (vinculado a Instituição)'},
        ),
        migrations.AlterModelOptions(
            name='tipologiadocumental',
            options={'verbose_name_plural': 'Tipologia documental'},
        ),
        migrations.AlterField(
            model_name='periodohistorico',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término do período hístorico da Instituição'),
        ),
        migrations.AlterField(
            model_name='periodohistorico',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de iníco do período hístorico da Instituição'),
        ),
        migrations.AlterField(
            model_name='periodohistorico',
            name='denominacao',
            field=models.CharField(max_length=250, verbose_name='Denominação do Período Histórico da Instituição'),
        ),
        migrations.AlterField(
            model_name='periodohistorico',
            name='gestor_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.gestormaior', verbose_name='Nome do cargo máximo no Período'),
        ),
        migrations.AlterField(
            model_name='periodohistorico',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo da Hístoria da Instituição no perrído'),
        ),
        migrations.AlterField(
            model_name='periodohistorico',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.orgaoatual', verbose_name='Nome da Instituição no Período'),
        ),
        migrations.AlterField(
            model_name='periodohistoricoparte',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término do período hístorico do Órgão/Unidade'),
        ),
        migrations.AlterField(
            model_name='periodohistoricoparte',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de inicio do período hístorico do Órgão/Unidade'),
        ),
        migrations.AlterField(
            model_name='periodohistoricoparte',
            name='denominacao_da_parte',
            field=models.CharField(max_length=250, verbose_name='Denominação do período Histórico do Órgão/Unidade (vinculado a Instituição)'),
        ),
        migrations.AlterField(
            model_name='periodohistoricoparte',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facetas.orgaounidade', verbose_name='Nome do Órgão/Unidade no Período'),
        ),
        migrations.AlterField(
            model_name='periodohistoricoparte',
            name='resumo',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo da hístoria do Órgão/Unidade no perrído'),
        ),
        migrations.CreateModel(
            name='FuncionalidadeDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório?')),
                ('instrucoes', models.TextField(blank=True, verbose_name='Instruções Específicas')),
                ('configuracao_funcional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facetas.configuracaofuncional', verbose_name='Configuração Funcional')),
                ('tipologia_documental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facetas.tipologiadocumental', verbose_name='Tipologia Documental')),
            ],
            options={
                'verbose_name_plural': '05 - Faceta Tipologia documental',
            },
        ),
    ]
